signatures = ["c6adb8b83c6d4c17d292afde56fd488a51d316ff8f2c11c5410223bff8a7dbb3"]
source = "GrapheneOS"
hasFsVeritySignatures = true
group = "Vanadium"
noIcon = true
isTopLevel = false
deps = ["app.vanadium.trichromelibrary", "app.vanadium.config"]
staticDeps = ["app.vanadium.webview >= 548106100"]
