signatures = ["c6adb8b83c6d4c17d292afde56fd488a51d316ff8f2c11c5410223bff8a7dbb3"]
source = "GrapheneOS"
group = "Vanadium"
noIcon = true
isTopLevel = false
deps = ["app.vanadium.browser", "app.vanadium.trichromelibrary"]
staticDeps = ["app.vanadium.browser >= 541411800"]
