#!/bin/bash

set -o errexit -o nounset -o pipefail

./process-static

servers=(
    0.releases.grapheneos.org
    1.releases.grapheneos.org
    2.releases.grapheneos.org
    3.releases.grapheneos.org
    4.releases.grapheneos.org
    5.releases.grapheneos.org
    6.releases.grapheneos.org
    7.releases.grapheneos.org
)

for server in ${servers[@]}; do
    echo $server

    remote=root@$server
    active=$(ssh $remote readlink /srv/apps.grapheneos.org)

    if [[ $active = /srv/apps.grapheneos.org_a ]]; then
        target=/srv/apps.grapheneos.org_b
    else
        target=/srv/apps.grapheneos.org_a
    fi

    echo active is $active
    echo target is $target
    echo

    ssh $remote rm -rf $target
    ssh $remote cp -a $active $target
    rsync -rptcv --chmod=D755,F644 --delete static-tmp/ $remote:$target
    ssh $remote sync -f $target
    ssh $remote ln -snf $target /srv/apps.grapheneos.org
    ssh $remote sync /srv/apps.grapheneos.org

    echo "root $target;" > root_apps.grapheneos.org.conf
    rsync -rptcv --chmod=D755,F644 --delete root_apps.grapheneos.org.conf $remote:/etc/nginx/root_apps.grapheneos.org.conf
    ssh $remote sync -f /etc/nginx/root_apps.grapheneos.org.conf
    ssh $remote nginx -s reload

    echo
    echo active is now $target
    echo
done
