#!/bin/bash

set -o errexit -o nounset -o pipefail

./process-static

servers=({0..7}.releases.grapheneos.org)

for server in ${servers[@]}; do
    echo $server

    remote=root@$server
    active=$(ssh $remote readlink /srv/apps.grapheneos.org)

    if [[ $active = /srv/apps.grapheneos.org_a ]]; then
        target=/srv/apps.grapheneos.org_b
    else
        target=/srv/apps.grapheneos.org_a
    fi

    echo active is $active
    echo target is $target
    echo

    ssh $remote "rm -rf $target && cp -a $active $target"
    rsync -rptcv --chmod=D755,F644 --delete static-tmp/ $remote:$target
    ssh $remote "sync -f $target && ln -snf $target /srv/apps.grapheneos.org && sync /srv/apps.grapheneos.org"

    echo "root $target;" > root_apps.grapheneos.org.conf
    rsync -rptcv --chmod=D755,F644 --delete root_apps.grapheneos.org.conf $remote:/etc/nginx/root_apps.grapheneos.org.conf
    ssh $remote "sync -f /etc/nginx/root_apps.grapheneos.org.conf && nginx -s reload"

    echo
    echo active is now $target
    echo
done
