#!/bin/bash

set -o errexit -o nounset -o pipefail -x

adb shell settings put global gmscompat_bypass_sys_component_update_stub 1
adb shell settings put global gmscompat_play_store_fetch_all_locales .+
adb shell settings put global gmscompat_play_store_can_install_com.google.android.gms 1
adb shell settings put global gmscompat_play_store_can_install_com.google.android.projection.gearhead 1
adb shell settings put global gmscompat_play_store_can_install_com.android.vending 1
