signatures = ["7ce83c1b71f3d572fed04c8d40c5cb10ff75e6d87d9df6fbd53f0468c2905053", "5f2391277b1dbd489000467e4c2fa6af802430080457dce2f618992e9dfb5402"]
source = "Google"

staticDeps = ["app.grapheneos.gmscompat >= 1000"]
# GSF is not needed on SDK 35+, it's excluded there by "android <= 34" staticDep.
# SkipIfMissing dependency flag makes App Store ignore GSF dependency on SDK 35+.
deps2 = ["com.google.android.gsf 0 SkipIfMissing", "com.android.vending"]
# deps property is ignored by App Store versions that support the new deps2 property
deps = ["com.google.android.gsf", "com.android.vending"]
requestUpdateOwnership = false

description = """
Official release of Google Play services without modifications. On GrapheneOS, it runs as a regular sandboxed app with no special access or privileges thanks to our sandboxed Google Play compatibility layer. The lack of any of the extensive standard privileged integration into the OS and the compatibility layer teaching it how to function that way are what makes it sandboxed Google Play.
"""
