signatures = ["f79e5f0ec0a0855efd2027e05eb9ec9c196d5d047940be603576e530867c3845"]
source = "GrapheneOS"
hasFsVeritySignatures = true
staticDeps = ["com.android.messaging >= 10001044"]

description = """SMS/MMS app providing compatibility with non-private carrier-based messaging. Use a secure messaging app such as Molly/Signal for privacy instead. This is a GrapheneOS fork of the Android Open Source Project Messaging app and still uses the AOSP package name for backwards compatibility."""
